name: hourly_jobs

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */6 * * *'  


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    - name: Run Docker container
      run: |
        cd $GITHUB_WORKSPACE
        mkdir img
        cd img
        wget https://github.com/aydkschen/hourly_get_info/releases/download/latest/xui_img.tar.gz
        # tar -zxvf xui_img.tar.gz
        # docker load -i xui.tar
        cat xui.tar.gz | docker import - xui:latest
        
        cd $GITHUB_WORKSPACE
        docker network create --subnet=172.18.0.0/16 my_custom_network

        # 启动 Docker 容器
        sudo docker run -itd --name xui --net my_custom_network --ip 172.18.0.12 xui:latest /usr/local/x-ui/x-ui
        sudo docker run -itd --name cf --net my_custom_network --ip 172.18.0.10 cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiYWZjODQ0MzQ0YzNhZGE5ODM3MzgzYjFlNDQzYjg3YWEiLCJ0IjoiMTQyZDMzMWMtYWUzZC00ZGJkLThhYzktZDJlNzY2YTAxYmFiIiwicyI6Ill6YzRNRGhpWVRBdE0yRmpOQzAwWW1RNUxUbGhOVFF0WXpSbE16WmlOMlF5TXpOaiJ9
        ip add
        sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' cf

        sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' xui
    - name: 保活
      run: |
        cd $GITHUB_WORKSPACE
        sudo chmod +x run_docker.sh
        sudo bash run_docker.sh
        sudo docker ps -a
        
    - name: restart and upload
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} > token.txt
        gh auth login --with-token < token.txt
        rm token.txt
        gh release delete latest
        gh release create latest xui_img.tar.gz
